add_newline = true
scan_timeout = 12

[character]
success_symbol = "[▶](bold green)"
error_symbol   = "[▶](bold red)"

[cmd_duration]
format = "🕛 [$duration](bold yellow)"
min_time = 500

[directory.substitutions]
"Developments" = " Developments"
"Dropbox" = " Dropbox"
"zenn-articles" = "󱀈 Articles"
"zenn-books" = " Books"
"~" = " Home"

[package]
disabled = true

[time]
disabled = true
format = '🕙 [\[ $time \]]($style) '
time_format = "%T"
use_12hr = true

[username]
show_always = false
style_root = "black bold"
style_user = "white bold"

[gcloud]
disabled = true
