# .github/workflows/macos.yml
name: macOS

on:
  push:
    branches:
      - main

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: /bin/bash bootstrap.sh  && \ echo y