# .github/workflows/macos.yml
name: macOS

on:
  push:
    branches:
      - main
    paths:
      - 'install-mac.sh'

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: bash bootstrap.sh